[workpackages]
token= 'https://plan.openheidelberg.de'
apikey = 'key'
ical_token = 'token'

[calendar]
url = "https://nx.openheidelberg.de/remote.php/dav/pubtoken-calendars/cEeeKR9xGJ6E66GC?export"

[matrix]
token = "token"
homeserver = "https://matrix.org"  # it is important that you use the full URL here
user_id = "@oh-bot:matrix.org"                                        
device_id = "altstadt"
command_prefix = "!"                                                  
case_insensitive = true                                               
owner_id = ""                                     
ignore_self = true

[client]
library = "mcp_use"  # "mcp_use" or "anthropic"
provider = "ollama"  # "ollama" or "anthropic"
model = "qwen3"  # "qwen3" or "claude-3-sonnet-20240229"
