[project]
name = "mcp-openheidelberg"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "ics>=0.7.2",
    "mcp[cli]>=1.10.1",
    "pytest>=8.4.1",
    "requests>=2.32.4",
    "toml>=0.10.2",
]
